### ISSUE TITLE
Section on match operator seems to be incorrect

### ISSUE THREAD

**Issue by digitalcohesion** [wintermeyer/elixir-phoenix-ash#35]
I do not get the match error described. Perhaps the behavior has changed? I have started with elixir recently so I'm not familiar with much history, but I was very surprised to see the example of the match error in this section and was not able to reproduce it.

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> x = 5
5
iex(2)> x = 7
7

**Comment by wintermeyer** [comment]
Thank you @digitalcohesion. This used to be true with old Elixir versions but isn't any more. I fixed the code.
