### ISSUE TITLE
The result of running the string interpolation in the elixir guide is different from the example.

### ISSUE THREAD

**Issue by j0urneyK** [wintermeyer/elixir-phoenix-ash#38]
Hello. Thank you for writing such a great guide.

I am currently working my way through the Elixir guide and I am not getting the same results when I run the example in [String Interpolation](https://elixir-phoenix-ash.com/elixir/index.html#_string_interpolation) locally.

In the first cell in the following image, I expected to get something like `"The list is [72, 101, 108, 108, 111]."`, but I am getting something like `"The list is Hello"`.

The second Cell expects to get a result like `"The tuple is {72, 101, 108, 108, 108, 111}."` when executed, but gets a `Protocol.UndefinedError` error.

![livebook-result](https://github.com/wintermeyer/elixir-phoenix-ash/assets/62772873/c9fb6829-4e6a-4ef7-ac84-a6330e173c99)

I suspected it was an issue with the Livebook environment, so I tried running it through iex, but I'm getting the same results as when I ran it in Livebook.

![iex-result](https://github.com/wintermeyer/elixir-phoenix-ash/assets/62772873/51a0c52c-f130-44f8-9f47-3a2ae5005ec1)

**Comment by wintermeyer** [comment]
Thank you for your bug report! I really appreciate it.

I removed the buggy example. It worked with older Elixir versions but doesn't any more.
