### ISSUE TITLE
The example code in `Pattern Matching With Various Data Structures` in Elixir in the Elixir guide is not running correctly.

### ISSUE THREAD

**Issue by j0urneyK** [wintermeyer/elixir-phoenix-ash#40]
Hello.

While looking at `Pattern Matching With Various Data Structures` in Elixir in the Elixir guide, I ran the following example code locally and did not get the same result as the example.

### Example Code

```elixir
defmodule User do
  def greet(name, opts \\ []) do
    greet(name, opts)
  end

  defp greet(name, [role: "admin"]) do
    "Welcome, #{name}. You have admin privileges."
  end

  defp greet(name, [role: "moderator"]) do
    "Welcome, #{name}. You can moderate content."
  end

  defp greet(name, _) do
    "Welcome, #{name}."
  end
end

IO.puts User.greet("Alice") # Outputs: "Welcome, Alice."

IO.puts User.greet("Bob", role: "admin") # Outputs: "Welcome, Bob. You have admin privileges."

IO.puts User.greet("Carol", role: "moderator") # Outputs: "Welcome, Carol. You can moderate content."
```

### My Local Result

![screenshot](https://github.com/wintermeyer/elixir-phoenix-ash/assets/62772873/4f90a0c4-b0ce-497d-bc5f-eb93f769d6ad)

If the content of the example code is not available in the latest version of Elixir, what is the latest alternative approach?

**Comment by wintermeyer** [comment]
Thank you for reporting this bug. I fixed the code example. It will be online in a couple of minutes. Thank you!

https://elixir-phoenix-ash.com/elixir/index.html#_pattern_matching_with_various_data_structures
