### ISSUE TITLE
Pattern matching on keyword lists is discouraged

### ISSUE THREAD

**Issue by mardukbp** [wintermeyer/elixir-phoenix-ash#46]
In the page https://github.com/wintermeyer/elixir-phoenix-ash/blob/main/modules/ROOT/pages/elixir/operators/match-operator.adoc it is stated

> Pattern matching with keyword lists is particularly useful for function arguments, as it allows us to capture specific items in the list without having to know the exact order or the entire content of the list.

Which is in contradiction with the Elixir documentation:

[Version 1.15](https://hexdocs.pm/elixir/1.15.0/Keyword.html#module-duplicate-keys-and-ordering)

> Given ordering is not guaranteed, it is not recommended to pattern match on keyword lists either.

[Version 1.17.3](https://hexdocs.pm/elixir/1.17.3/keywords-and-maps.html)

> Although we can pattern match on keyword lists, it is not done in practice since pattern matching on lists requires the number of items and their order to match. Furthermore, given keyword lists are often used as optional arguments, they are used in situations where not all keys may be present, which would make it impossible to match on them. In a nutshell, do not pattern match on keyword lists.

**Comment by wintermeyer** [comment]
@mardukbp Thanks again! Big help! I really appreciate your work here.
